### ISSUE TITLE
c: define Clang integer-limit builtin macros for resource headers

### ISSUE THREAD

**Issue by davidgmbb** [buster14a/buster#607]
## Reproduced defect

The pinned CPython v3.13.9 compatibility harness cannot reach its regression suite with the repository's Clang 18.1.3 resource headers because Buster does not define Clang's `__LONG_LONG_MAX__` predefined macro.

Reproduced on frozen main `14da1343e96ea08007842bc9a67202e36c9ee02c` (tree `250ac2b8d77eb48012e5db052a50d35c96207f62`) and independently on #80 candidate tree `a685c0835a388d4a37b6bb853032d276db19a66d`. Both fail the same object-only compile:

```
ide cc ... -DPy_BUILD_CORE_BUILTIN -c   CPython-v3.13.9/Modules/_blake2/blake2s_impl.c   -o Modules/_blake2/blake2s_impl.o

cc: error: .../clang/18/include/avx512fintrin.h:9486:50:
use of undeclared identifier '__LONG_LONG_MAX__'
```

The sibling `blake2b_impl.c` object fails at the same header. The pristine CPython input is tag v3.13.9, commit `8183fa5e3f78ca6ab862de7fb8b14f3d929421e0`. The Clang reference configure/build passes. Buster's configure and the separately compiled `Python/perf_jit_trampoline.o` pass; the first full Buster FAST make then fails on these two objects.

This is not caused by #80: the command is `-c`, never reaches executable ELF linking, and the frozen-main compiler produces the identical diagnostic.

## Start here

Predefined target/compiler macros are assembled in `src/buster/lib/compiler/frontend/c/c_source.c` near the existing `__LONG_LONG_WIDTH__` and size macros. Inspect the effective Clang resource-header contract rather than special-casing CPython or editing the pristine headers.

Ownership warning: recheck current frontend branches, including prepared-parameter/local-alignment work, before changing shared frontend files.

## Impact

The registered opt-in `test_cpython` gate cannot reach workload or `test_gdb` verification under this supported Clang 18 resource-header configuration. This currently blocks the pinned compatibility acceptance for #80 even though its executable symbol-table behavior passes independent readelf/nm/objdump/GDB file inspection.

## Acceptance

- Add the missing predefined integer-limit macro(s) with target-correct type/value semantics across LP64 and LLP64, not just a textual CPython workaround.
- Compare Buster's relevant predefined macro set and values against supported Clang/GCC targets; preserve `-funsigned-char`, target layouts, MSVC, AArch64, and self-hosting.
- Add focused registered preprocessing/compile tests using the actual resource header or a minimal independent assertion that checks value, spelling/type behavior, and conditional use.
- Rerun the exact two CPython BLAKE2 object compilations, then the pristine pinned CPython harness.
- Run registered tests, supported compiler/configuration checks, sanitizer coverage, and self-host fixed point on the submitted head.

Searches for `__LONG_LONG_MAX__`, `LONG_LONG_MAX`, `avx512fintrin`, and CPython BLAKE2 issues/branches returned no matching implementation owner or prior defect; no source fix was attempted here.

**Comment by davidgmbb** [comment]
Coordination claim for the current non-#36 PR completion stream.

Frozen writable base: current main `e5620bc16f675d9165d175fceb38c317c5d2ff8c` (tree `d71666f861b1db17420a6077af1401fced9e6422`, rechecked 2026-09-14). Main advanced from the earlier `68eaf757` navigation snapshot only through #622's documentation/license files; no compiler or test path overlaps this slice. Live searches again found no #607 branch/PR/comment beyond this claim or matching `__LONG_LONG_MAX__` implementation owner. This is not an atomic lock; ownership and head will be rechecked before publication.

Objective: define the relevant Clang-compatible integer-limit builtins with target-correct value and type semantics across LP64/LLP64 so the exact pinned CPython BLAKE2 objects compile and #606 can reach test_gdb.

Allowed surface: the existing predefined-macro construction in `src/buster/lib/compiler/frontend/c/c_source.c` near `__LONG_LONG_WIDTH__`, and the narrow existing registered frontend/preprocessor test seam needed to assert spelling, value, type/conditional behavior and target layouts. Forbidden: #600 once-file/index/import/include/guard regions and its registration files; `c_gen.c`; native backend/#36; linker/#606; workflows/CI-speedup paths; pristine CPython/resource headers.

Acceptance gates: failure-first object/macro reproduction, LP64 and LLP64 plus x86-64/AArch64 target checks, focused registered tests, warnings-as-errors, sanitizer and Release self-host, exact two CPython BLAKE2 objects, then pinned CPython as resources permit. Sol High implements in an isolated worktree; Luna Max independently reviews the submitted patch/tree. Resource budget is local isolated build roots only; no reserved benchmark host or workflow mutation.

**Comment by davidgmbb** [comment]
Focused acceptance update for #624 (exact head `0c9ccd51d67ea69175ce0c1c4128a0a74fda6f3b`, tree `2dd50d17f349d5503f559d2fb0a11c634b5f730b`):

- A fresh pristine CPython v3.13.9 checkout at `8183fa5e3f78ca6ab862de7fb8b14f3d929421e0` configured successfully with a Buster FAST compiler built from the submitted tree and LLVM `llvmorg-18.1.3` resource headers.
- The exact generated `make -j1 V=1` recipes for both `blake2s_impl.o` and `blake2b_impl.o` now pass the original `__LONG_LONG_MAX__` failure point.
- Both then fail at the newly exposed `avx512fp16intrin.h:37` because Buster has no real `_Float16` type and loses the parameter in `_Float16 f(_Float16 a) { return a; }`.

The independent blocker is filed as #631 with its reduction and ownership boundary. No CPython or resource header was modified. #624 remains draft; this is successful evidence for the scoped macro repair, not a pass for the two-object or full harness acceptance gate. Hosted GPU, throughput, and self-host workflows have passed; Buster CI is still completing.

**Comment by davidgmbb** [comment]
Measured evidence for the "compare Buster's relevant predefined macro set" half of the acceptance, in case it is useful to #624.

Hit this while implementing #631: to reach the FP16 header at all I had to supply the limit macros on the command line. On the current default branch (`c96696e`, i.e. without #624), every one of these is undefined, not just `__LONG_LONG_MAX__`:

```
__SCHAR_MAX__      MISSING
__SHRT_MAX__       MISSING
__INT_MAX__        MISSING
__LONG_MAX__       MISSING
__LONG_LONG_MAX__  MISSING
__WCHAR_MAX__      MISSING
__INTMAX_MAX__     MISSING
__SIZE_MAX__       MISSING
__UINT32_MAX__     MISSING
```

probed as `#ifndef <name>` / `#error missing` per macro, target `x86_64-linux`.

They also surface in order within the same header: defining `__LONG_LONG_MAX__` alone moves the failure from `avx512fintrin.h:9486` to `avx512fintrin.h:9529`, which wants `__INT_MAX__`. So a fix that adds only the macro this issue names will reproduce as a new defect one line later.

With `-D__LONG_LONG_MAX__ -D__INT_MAX__ -D__SCHAR_MAX__ -D__SHRT_MAX__ -D__LONG_MAX__` supplied, the pinned `immintrin.h` clears `avx512fintrin.h` entirely and stops at `avx512fp16intrin.h:37` — which is the #631 defect, now fixed in PR #670 — and then at `avx512bf16intrin.h:40`, filed as #671.

No change proposed here; this is only the macro list and the ordering evidence.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by davidgmbb** [comment]
## #624 review follow-up — acceptance retained here

Updated #624's description in response to the exact-head review. Its automatic-closing reference was removed and replaced with a non-closing relationship to this issue. **This issue's original acceptance requirements are unchanged and remain open.**

Revision: `b45909903215a415564cdc43569cea516e8bd721`, tree `2d762e6109aae352a19002724caf81628acb2884`. The PR test-merge commit `0528f74a09f957de0f6972de88aef6823f6874ec` has exactly the same tree, verified through GitHub's Git commit API.

Last checked current-head workflows on September 16, 2026:

- Self-host fixed point [35111051878](https://github.com/buster14a/buster/actions/runs/35111051878): success.
- Compiler throughput [35111051948](https://github.com/buster14a/buster/actions/runs/35111051948): success.
- GPU toolchain acceptance [35111052011](https://github.com/buster14a/buster/actions/runs/35111052011): success.
- Buster CI [35111051987](https://github.com/buster14a/buster/actions/runs/35111051987): still in progress, not a pass.

Old-head `0c9ccd51...` validation is now explicitly labeled historical in #624. #631 is closed/completed; it is no longer asserted as a current blocker. The BF16 report in the preceding comment is also a lead, not a new reproduction on this head.

### Outstanding current-head acceptance

- [ ] Successful completion of Buster CI, including applicable compiler/configuration and sanitizer coverage.
- [ ] Fresh exact generated `make -j1 V=1 Modules/_blake2/blake2s_impl.o` recipe.
- [ ] Fresh exact generated `make -j1 V=1 Modules/_blake2/blake2b_impl.o` recipe.
- [ ] Registered pristine pinned CPython harness: `./build.sh test_cpython --config Release /path/to/cpython-v3.13.9`.
- [ ] Publish compiler head/tree, commands, exit statuses and logs; record any actual next blocker separately without modifying upstream inputs or relaxing the gate.

Pins remain CPython `v3.13.9` / `8183fa5e3f78ca6ab862de7fb8b14f3d929421e0` and LLVM resource headers `llvmorg-18.1.3` / `c13b7485b87909fcf739f62cfa382b55407433c0`.

Execution limitation: the successful self-host run's artifact `10452223830` was downloaded through the GitHub connection, but container/Python execution returned `TransportTimeoutError` before its contents could be inspected. Consequently no Buster compiler, BLAKE2 recipe, or CPython harness was run in this follow-up. These gates remain **unverified**, not failed and not passed. No new CI run, source commit, branch update, or merge was performed.
